"""
Seed script — populates the database with all 20 NOC buildings,
fire stations, and building-station mappings.

Run once: python seed.py
"""

import asyncio
from datetime import date
from database import engine, async_session, Base
from models import Building, FireStation, BuildingStationMap


# ── All 20 buildings from NOC PDF ──

BUILDINGS = [
    {
        "building_id": "THN-001",
        "name": "Somaiya Vidyavihar University",
        "building_type": "Educational — University",
        "address": "Vidyavihar, Kurla West, Mumbai – 400077",
        "nearest_landmark": "Eastern Express Highway, near Vidyavihar Station",
        "nbc_occupancy_group": "Group B — Educational",
        "floors_above_ground": 8,
        "floors_below_ground": 1,
        "total_height_metres": 32.0,
        "plot_area_sqm": 26000.0,
        "built_up_area_sqm": 18400.0,
        "daytime_occupancy": 12000,
        "nighttime_occupancy": 400,
        "fire_alarm_make": "Honeywell Morley IAS — Addressable",
        "sprinkler_system": "Yes — wet pipe throughout",
        "internal_hydrants": 14,
        "external_hydrants": 6,
        "wet_riser": "Yes — 4 risers",
        "fire_extinguishers": "CO2 and dry powder — 180 units",
        "panel_model": "Morley-IAS ZXe Series",
        "detection_zones": 64,
        "fire_pump_capacity": "1500 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — fully addressable",
        "generator_backup": "Yes — 100% fire system",
        "amc_vendor": "Securitas India Pvt Ltd",
        "amc_valid_till": date(2025, 3, 31),
        "last_fire_drill": date(2024, 9, 15),
        "drill_attendance_pct": 94,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2019/1142",
        "architect": "Hafeez Contractor Associates",
        "mep_consultant": "Spectral Engineers Pvt Ltd",
        "refuge_floors": "4th and 8th floor",
        "owner_name": "Somaiya Vidyavihar Educational Trust",
        "owner_contact": "022-67283001",
        "entry_points": "Main gate (Vidyavihar Road), Service gate (East wing), Emergency gate (North perimeter)",
        "exit_routes": "8 staircases, 4 emergency exits, 2 refuge areas",
        "previous_noc_number": "THN/NOC/2023/0812",
        "previous_violations": "None",
        "first_contact_on_site": "Security Control Room — 022-67283000",
        "last_inspection_date": date(2024, 10, 12),
        "inspecting_officer": "Sub Officer R.K. Patil",
        "noc_number": "THN/NOC/2024/0891",
        "noc_valid_till": date(2025, 3, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.0728,
        "longitude": 72.8998,
    },
    {
        "building_id": "THN-002",
        "name": "Jupiter Hospital",
        "building_type": "Institutional — Private Hospital",
        "address": "Eastern Express Highway, Thane West – 400601",
        "nearest_landmark": "Opposite Viviana Mall, Thane",
        "nbc_occupancy_group": "Group C — Institutional",
        "floors_above_ground": 12,
        "floors_below_ground": 2,
        "total_height_metres": 48.0,
        "plot_area_sqm": 8200.0,
        "built_up_area_sqm": 14600.0,
        "daytime_occupancy": 2800,
        "nighttime_occupancy": 1200,
        "fire_alarm_make": "Siemens Cerberus — Addressable",
        "sprinkler_system": "Yes — full coverage wet pipe",
        "internal_hydrants": 18,
        "external_hydrants": 8,
        "wet_riser": "Yes — 6 risers",
        "fire_extinguishers": "CO2, dry powder, water mist — 240 units",
        "panel_model": "Siemens FC2060 Cerberus PRO",
        "detection_zones": 128,
        "fire_pump_capacity": "2250 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — zone-wise addressable",
        "generator_backup": "Yes — 100%, 48hr fuel",
        "amc_vendor": "Siemens Building Technologies India",
        "amc_valid_till": date(2025, 2, 28),
        "last_fire_drill": date(2024, 7, 20),
        "drill_attendance_pct": 88,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2016/0834",
        "architect": "HCP Design and Project Management",
        "mep_consultant": "Consulting Engineers Group",
        "refuge_floors": "6th and 12th floor",
        "owner_name": "Jupiter Life Line Hospitals Ltd",
        "owner_contact": "0251-6626201",
        "entry_points": "Main entrance (EEH), Emergency entrance (South), Ambulance bay (East), Service entry (West)",
        "exit_routes": "6 staircases, 2 fire escapes, 4 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0401",
        "previous_violations": "Minor — fire door obstruction (rectified June 2024)",
        "first_contact_on_site": "Security Desk (24hr) — 0251-6626200",
        "last_inspection_date": date(2024, 8, 8),
        "inspecting_officer": "Sub Officer S.V. Mane",
        "noc_number": "THN/NOC/2024/0445",
        "noc_valid_till": date(2025, 2, 28),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2094,
        "longitude": 72.9730,
    },
    {
        "building_id": "THN-003",
        "name": "Viviana Mall",
        "building_type": "Mercantile — Shopping Mall",
        "address": "Pokhran Road No. 2, Thane West – 400610",
        "nearest_landmark": "Near Thane Station, EEH junction",
        "nbc_occupancy_group": "Group F — Mercantile",
        "floors_above_ground": 5,
        "floors_below_ground": 3,
        "total_height_metres": 22.0,
        "plot_area_sqm": 42000.0,
        "built_up_area_sqm": 156000.0,
        "daytime_occupancy": 35000,
        "nighttime_occupancy": 0,
        "fire_alarm_make": "Honeywell Notifier — Addressable",
        "sprinkler_system": "Yes — full coverage, 6200 heads",
        "internal_hydrants": 62,
        "external_hydrants": 20,
        "wet_riser": "Yes — 12 risers",
        "fire_extinguishers": "CO2, dry powder, K-class — 480 units",
        "panel_model": "Notifier NFS2-3030",
        "detection_zones": 256,
        "fire_pump_capacity": "4500 LPM at 3.5 kg/cm2 — 3 pumps",
        "public_address_system": "Yes — fully integrated public address",
        "generator_backup": "Yes — 100%, 72hr diesel",
        "amc_vendor": "Warden Fire Protection Pvt Ltd",
        "amc_valid_till": date(2025, 1, 15),
        "last_fire_drill": date(2024, 10, 5),
        "drill_attendance_pct": 91,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2013/0221",
        "architect": "RSP Architects",
        "mep_consultant": "Meinhardt India Pvt Ltd",
        "refuge_floors": "N/A — low rise",
        "owner_name": "Viviana Malls Pvt Ltd",
        "owner_contact": "0251-6690001",
        "entry_points": "4 main entrances (N/S/E/W), 2 service entrances, basement parking (East and West ramps)",
        "exit_routes": "16 staircases, 12 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0098",
        "previous_violations": "None",
        "first_contact_on_site": "Security Command Centre (24hr) — 0251-6690000",
        "last_inspection_date": date(2024, 6, 3),
        "inspecting_officer": "Div. Officer P.D. Kamble",
        "noc_number": "THN/NOC/2024/0112",
        "noc_valid_till": date(2025, 1, 15),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2085,
        "longitude": 72.9760,
    },
    {
        "building_id": "THN-004",
        "name": "Hiranandani Estate — Tower A & B",
        "building_type": "Residential — High Rise",
        "address": "Patlipada, Ghodbunder Road, Thane West – 400607",
        "nearest_landmark": "Ghodbunder Road, near Hiranandani Hospital",
        "nbc_occupancy_group": "Group A — Residential",
        "floors_above_ground": 32,
        "floors_below_ground": 3,
        "total_height_metres": 98.0,
        "plot_area_sqm": 3800.0,
        "built_up_area_sqm": 22400.0,
        "daytime_occupancy": 640,
        "nighttime_occupancy": 920,
        "fire_alarm_make": "Siemens Sinteso — Addressable",
        "sprinkler_system": "Yes — wet pipe above 7th floor",
        "internal_hydrants": 32,
        "external_hydrants": 4,
        "wet_riser": "Yes — 4 pressurised risers",
        "fire_extinguishers": "CO2 and dry powder — 128 units",
        "panel_model": "Siemens FS20 Sinteso",
        "detection_zones": 96,
        "fire_pump_capacity": "1800 LPM at 4.5 kg/cm2",
        "public_address_system": "Yes — floor-wise",
        "generator_backup": "Yes — fire lifts and fire system",
        "amc_vendor": "Siemens Building Technologies India",
        "amc_valid_till": date(2025, 4, 30),
        "last_fire_drill": date(2024, 11, 12),
        "drill_attendance_pct": 72,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2018/0991",
        "architect": "Hafeez Contractor Associates",
        "mep_consultant": "Spectral Engineers Pvt Ltd",
        "refuge_floors": "9th, 18th, 27th floor",
        "owner_name": "Hiranandani Communities Pvt Ltd",
        "owner_contact": "0251-2580101",
        "entry_points": "Main lobby (Ghodbunder Road), Podium entry (East), Service entry (Rear north)",
        "exit_routes": "4 pressurised staircases, 2 fire escapes per tower",
        "previous_noc_number": "THN/NOC/2023/1188",
        "previous_violations": "None",
        "first_contact_on_site": "Lobby Security (24hr) — 0251-2580100",
        "last_inspection_date": date(2024, 11, 19),
        "inspecting_officer": "Sub Officer A.B. Shinde",
        "noc_number": "THN/NOC/2024/1203",
        "noc_valid_till": date(2025, 4, 30),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2590,
        "longitude": 72.9670,
    },
    {
        "building_id": "THN-005",
        "name": "Thane Municipal Corporation — Main Office",
        "building_type": "Assembly — Government Office",
        "address": "Dr. Moreshwar Save Marg, Naupada, Thane West – 400602",
        "nearest_landmark": "Near Thane Station, Naupada junction",
        "nbc_occupancy_group": "Group D — Assembly",
        "floors_above_ground": 6,
        "floors_below_ground": 1,
        "total_height_metres": 24.0,
        "plot_area_sqm": 5600.0,
        "built_up_area_sqm": 9800.0,
        "daytime_occupancy": 3200,
        "nighttime_occupancy": 40,
        "fire_alarm_make": "Conventional Zone — Bosch",
        "sprinkler_system": "No",
        "internal_hydrants": 8,
        "external_hydrants": 4,
        "wet_riser": "Yes — 2 risers",
        "fire_extinguishers": "CO2 and dry powder — 96 units",
        "panel_model": "Bosch FPA-1200",
        "detection_zones": 32,
        "fire_pump_capacity": "900 LPM at 3.5 kg/cm2",
        "public_address_system": "Partial — ground floor only",
        "generator_backup": "Yes — essential circuits only",
        "amc_vendor": "REMS Security Systems",
        "amc_valid_till": date(2025, 3, 31),
        "last_fire_drill": date(2024, 1, 26),
        "drill_attendance_pct": 85,
        "structural_stability": True,
        "occupancy_certificate": "OC/TMC/1998/0014",
        "architect": "PWD Maharashtra",
        "mep_consultant": "Maharashtra Fire Services Dept",
        "refuge_floors": "N/A",
        "owner_name": "Thane Municipal Corporation (Government)",
        "owner_contact": "0251-2582000",
        "entry_points": "Main entrance (Save Marg), Side entrance (East lane), Service entry (Rear — staff only)",
        "exit_routes": "4 staircases, 6 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0003",
        "previous_violations": "None",
        "first_contact_on_site": "Reception Security — 1800-210-1234",
        "last_inspection_date": date(2024, 1, 5),
        "inspecting_officer": "Sub Officer M.R. Jadhav",
        "noc_number": "THN/NOC/2024/0003",
        "noc_valid_till": date(2025, 3, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1960,
        "longitude": 72.9756,
    },
    {
        "building_id": "THN-006",
        "name": "K.B. Bhabha Hospital",
        "building_type": "Institutional — Government Hospital",
        "address": "Ram Maruti Road, Naupada, Thane West – 400602",
        "nearest_landmark": "Near Thane Civil Court, Ram Maruti Road",
        "nbc_occupancy_group": "Group C — Institutional",
        "floors_above_ground": 7,
        "floors_below_ground": 1,
        "total_height_metres": 28.0,
        "plot_area_sqm": 9200.0,
        "built_up_area_sqm": 11400.0,
        "daytime_occupancy": 1800,
        "nighttime_occupancy": 600,
        "fire_alarm_make": "Conventional Zone — Agni",
        "sprinkler_system": "Partial — ICU and OT only",
        "internal_hydrants": 12,
        "external_hydrants": 6,
        "wet_riser": "Yes — 3 risers",
        "fire_extinguishers": "CO2, dry powder, water — 160 units",
        "panel_model": "Agni FP-2400",
        "detection_zones": 48,
        "fire_pump_capacity": "1200 LPM at 3.5 kg/cm2",
        "public_address_system": "No",
        "generator_backup": "Yes — fire system and critical wards",
        "amc_vendor": "Safety Fire Engineers",
        "amc_valid_till": date(2025, 2, 28),
        "last_fire_drill": date(2024, 8, 1),
        "drill_attendance_pct": 79,
        "structural_stability": True,
        "occupancy_certificate": "OC/TMC/2004/0412",
        "architect": "PWD Maharashtra",
        "mep_consultant": "Maharashtra Fire Services Dept",
        "refuge_floors": "N/A",
        "owner_name": "Municipal Corporation — Thane Health Unit",
        "owner_contact": "0251-2302245",
        "entry_points": "Main gate (Ram Maruti Road), Emergency gate (South), Mortuary entry (Rear — restricted)",
        "exit_routes": "5 staircases, 3 emergency exits, wheelchair ramps on 2 exits",
        "previous_noc_number": "THN/NOC/2023/0204",
        "previous_violations": "Fire door missing on 3rd floor stairwell (rectified March 2024)",
        "first_contact_on_site": "Main Gate Security (24hr) — 0251-2302244",
        "last_inspection_date": date(2024, 7, 22),
        "inspecting_officer": "Sub Officer V.S. Gaikwad",
        "noc_number": "THN/NOC/2024/0218",
        "noc_valid_till": date(2025, 2, 28),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1972,
        "longitude": 72.9720,
    },
    {
        "building_id": "THN-007",
        "name": "Lodha Amara — Towers 1 to 4",
        "building_type": "Residential — High Rise Complex",
        "address": "Kolshet Road, Thane West – 400607",
        "nearest_landmark": "Kolshet Industrial Area, near Cadbury Junction",
        "nbc_occupancy_group": "Group A — Residential",
        "floors_above_ground": 45,
        "floors_below_ground": 4,
        "total_height_metres": 138.0,
        "plot_area_sqm": 12400.0,
        "built_up_area_sqm": 84000.0,
        "daytime_occupancy": 2800,
        "nighttime_occupancy": 4200,
        "fire_alarm_make": "Honeywell Morley IAS — Addressable",
        "sprinkler_system": "Yes — full coverage, 9800 heads across 4 towers",
        "internal_hydrants": 180,
        "external_hydrants": 12,
        "wet_riser": "Yes — 8 pressurised risers",
        "fire_extinguishers": "CO2 and dry powder — 420 units",
        "panel_model": "Morley-IAS ZXe Pro",
        "detection_zones": 192,
        "fire_pump_capacity": "3600 LPM at 4.5 kg/cm2 — 2 pumps per tower",
        "public_address_system": "Yes — fully integrated, floor-wise",
        "generator_backup": "Yes — 100%, 72hr diesel",
        "amc_vendor": "Honeywell Building Solutions India",
        "amc_valid_till": date(2025, 8, 31),
        "last_fire_drill": date(2024, 3, 18),
        "drill_attendance_pct": 68,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2022/1891",
        "architect": "Hafeez Contractor Associates",
        "mep_consultant": "WSP India Pvt Ltd",
        "refuge_floors": "12th, 24th, 36th floor per tower",
        "owner_name": "Lodha Developers Pvt Ltd",
        "owner_contact": "1800-2099-101",
        "entry_points": "Main gate (Kolshet Road), Secondary gate (East), Service gate (North boundary)",
        "exit_routes": "3 pressurised staircases per tower, fire lifts on each tower",
        "previous_noc_number": "THN/NOC/2023/0918",
        "previous_violations": "None",
        "first_contact_on_site": "Security Command Centre (24hr) — 1800-2099-100",
        "last_inspection_date": date(2024, 4, 7),
        "inspecting_officer": "Div. Officer H.K. Sawant",
        "noc_number": "THN/NOC/2024/0934",
        "noc_valid_till": date(2025, 8, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2310,
        "longitude": 72.9780,
    },
    {
        "building_id": "THN-008",
        "name": "Korum Mall",
        "building_type": "Mercantile — Shopping Mall",
        "address": "Eastern Express Highway, Thane West – 400601",
        "nearest_landmark": "EEH, near Cadbury Junction",
        "nbc_occupancy_group": "Group F — Mercantile",
        "floors_above_ground": 5,
        "floors_below_ground": 3,
        "total_height_metres": 22.0,
        "plot_area_sqm": 28000.0,
        "built_up_area_sqm": 98000.0,
        "daytime_occupancy": 25000,
        "nighttime_occupancy": 0,
        "fire_alarm_make": "Honeywell Notifier — Addressable",
        "sprinkler_system": "Yes — full coverage, 4200 heads",
        "internal_hydrants": 44,
        "external_hydrants": 14,
        "wet_riser": "Yes — 8 risers",
        "fire_extinguishers": "CO2, dry powder, K-class — 320 units",
        "panel_model": "Notifier NFS2-640",
        "detection_zones": 128,
        "fire_pump_capacity": "3600 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — zone-wise public address",
        "generator_backup": "Yes — 100%, 48hr diesel",
        "amc_vendor": "Fire Blaze India Pvt Ltd",
        "amc_valid_till": date(2025, 2, 28),
        "last_fire_drill": date(2024, 9, 14),
        "drill_attendance_pct": 87,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2012/0318",
        "architect": "RSP Design Consultants",
        "mep_consultant": "Meinhardt India Pvt Ltd",
        "refuge_floors": "N/A — low rise",
        "owner_name": "Korum Mall Management Pvt Ltd",
        "owner_contact": "0251-6626601",
        "entry_points": "Main entrance (EEH service road), Multiplex entrance (East), Parking ramps (Basement West and East)",
        "exit_routes": "10 staircases, 8 emergency exits, 2 dedicated fire escapes",
        "previous_noc_number": "THN/NOC/2023/0174",
        "previous_violations": "None",
        "first_contact_on_site": "Security Control Room (24hr) — 0251-6626600",
        "last_inspection_date": date(2024, 8, 29),
        "inspecting_officer": "Sub Officer N.T. Bhosale",
        "noc_number": "THN/NOC/2024/0190",
        "noc_valid_till": date(2025, 2, 28),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2183,
        "longitude": 72.9781,
    },
    {
        "building_id": "THN-009",
        "name": "Wagle Industrial Estate — Block 4",
        "building_type": "Industrial — Manufacturing (High Hazard)",
        "address": "MIDC Wagle Estate, Thane West – 400604",
        "nearest_landmark": "Near Balkum Naka, Wagle Estate MIDC",
        "nbc_occupancy_group": "Group G — Industrial",
        "floors_above_ground": 4,
        "floors_below_ground": 1,
        "total_height_metres": 16.0,
        "plot_area_sqm": 18000.0,
        "built_up_area_sqm": 32000.0,
        "daytime_occupancy": 1800,
        "nighttime_occupancy": 200,
        "fire_alarm_make": "Conventional Zone — Hochiki",
        "sprinkler_system": "Yes — deluge system in high hazard areas",
        "internal_hydrants": 20,
        "external_hydrants": 10,
        "wet_riser": "Yes — 4 risers",
        "fire_extinguishers": "CO2, dry powder, foam (AFFF) — 280 units",
        "panel_model": "Hochiki FireNET Plus",
        "detection_zones": 48,
        "fire_pump_capacity": "2700 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — zone-wise alarm",
        "generator_backup": "Yes — fire pump and alarm system",
        "amc_vendor": "Industrial Fire Protection Services",
        "amc_valid_till": date(2025, 4, 30),
        "last_fire_drill": date(2024, 10, 5),
        "drill_attendance_pct": 96,
        "structural_stability": True,
        "occupancy_certificate": "OC/MIDC/2009/0744",
        "architect": "MIDC Approved Contractor",
        "mep_consultant": "MIDC Fire Safety Cell",
        "refuge_floors": "N/A",
        "owner_name": "Wagle Estate Industrial Co-operative",
        "owner_contact": "0251-2763001",
        "entry_points": "Main security gate (MIDC Road), Goods vehicle gate (South), Emergency access gate (West boundary)",
        "exit_routes": "6 emergency exits, 2 muster assembly points (North and South yard)",
        "previous_noc_number": "THN/NOC/2023/0396",
        "previous_violations": "MSDS not current for 2 chemicals (rectified August 2024)",
        "first_contact_on_site": "Security Gate (24hr) — 0251-2763000",
        "last_inspection_date": date(2024, 10, 8),
        "inspecting_officer": "Sub Officer S.K. Tupe",
        "noc_number": "THN/NOC/2024/0411",
        "noc_valid_till": date(2025, 4, 30),
        "is_high_hazard": True,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2050,
        "longitude": 72.9580,
    },
    {
        "building_id": "THN-010",
        "name": "Bharat Petroleum Thane Terminal",
        "building_type": "Industrial — Petroleum Storage (EXTREME HAZARD)",
        "address": "Kalwa, Thane – 400605",
        "nearest_landmark": "Near Kalwa Bridge, Thane Creek, Kalwa MIDC",
        "nbc_occupancy_group": "Group H — Storage (High Hazard)",
        "floors_above_ground": 1,
        "floors_below_ground": 0,
        "total_height_metres": 18.0,
        "plot_area_sqm": 86000.0,
        "built_up_area_sqm": 12000.0,
        "daytime_occupancy": 180,
        "nighttime_occupancy": 40,
        "fire_alarm_make": "Siemens Cerberus Addressable + VESDA (Smoke Detection)",
        "sprinkler_system": "Yes — foam deluge system, 6 tank foam monitors",
        "internal_hydrants": 0,
        "external_hydrants": 32,
        "wet_riser": "No — foam ring main primary suppression",
        "fire_extinguishers": "CO2, dry powder, AFFF foam — 380 units. Trolley units at each tank.",
        "panel_model": "Siemens FC2080 + VESDA LaserFOCUS",
        "detection_zones": 64,
        "fire_pump_capacity": "6000 LPM at 7.0 kg/cm2 — dedicated foam pump station",
        "public_address_system": "Yes — site-wide emergency PA",
        "generator_backup": "Yes — 100%, 96hr diesel, dual redundancy",
        "amc_vendor": "Siemens Building Technologies India",
        "amc_valid_till": date(2025, 1, 31),
        "last_fire_drill": date(2024, 7, 10),
        "drill_attendance_pct": 100,
        "structural_stability": True,
        "occupancy_certificate": "OC/PESO/2011/0122",
        "architect": "BPCL Engineering Division",
        "mep_consultant": "BPCL Fire Safety and Petroleum Engineering",
        "refuge_floors": "N/A",
        "owner_name": "Bharat Petroleum Corporation Ltd (BPCL)",
        "owner_contact": "0251-2730001",
        "entry_points": "Main security gate (Kalwa Road — vehicle check), Tanker loading gate (East — restricted), Emergency access gate (North boundary)",
        "exit_routes": "6 emergency exits, 4 muster stations on perimeter, evacuation route to Kalwa Road",
        "previous_noc_number": "THN/NOC/2023/0024",
        "previous_violations": "None",
        "first_contact_on_site": "Security Control Room (24hr) — 0251-2730000",
        "last_inspection_date": date(2024, 7, 25),
        "inspecting_officer": "Div. Officer S.M. Wagh",
        "noc_number": "THN/NOC/2024/0027",
        "noc_valid_till": date(2025, 1, 31),
        "is_high_hazard": True,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1920,
        "longitude": 73.0030,
    },
    {
        "building_id": "THN-011",
        "name": "Fortis Hospital Mulund",
        "building_type": "Institutional — Private Hospital",
        "address": "Mulund Goregaon Link Road, Mulund West, Mumbai – 400080",
        "nearest_landmark": "LBS Marg junction, Mulund West",
        "nbc_occupancy_group": "Group C — Institutional",
        "floors_above_ground": 10,
        "floors_below_ground": 2,
        "total_height_metres": 40.0,
        "plot_area_sqm": 6800.0,
        "built_up_area_sqm": 12200.0,
        "daytime_occupancy": 2200,
        "nighttime_occupancy": 900,
        "fire_alarm_make": "Siemens Cerberus — Addressable",
        "sprinkler_system": "Yes — full building coverage",
        "internal_hydrants": 16,
        "external_hydrants": 6,
        "wet_riser": "Yes — 4 risers",
        "fire_extinguishers": "CO2, dry powder, water mist — 200 units",
        "panel_model": "Siemens FC2040 Cerberus PRO",
        "detection_zones": 96,
        "fire_pump_capacity": "1800 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — floor-wise addressable",
        "generator_backup": "Yes — 100%, 48hr fuel, UPS for critical systems",
        "amc_vendor": "Siemens Building Technologies India",
        "amc_valid_till": date(2025, 7, 31),
        "last_fire_drill": date(2024, 12, 22),
        "drill_attendance_pct": 91,
        "structural_stability": True,
        "occupancy_certificate": "OC/MCGM/2017/1244",
        "architect": "ARCOP Associates",
        "mep_consultant": "Spectral Engineers Pvt Ltd",
        "refuge_floors": "5th and 10th floor",
        "owner_name": "Fortis Healthcare Ltd",
        "owner_contact": "022-67124001",
        "entry_points": "Main entrance (LBS Marg), Emergency and casualty entrance (North), Service entry (Rear)",
        "exit_routes": "4 pressurised staircases, 2 external fire escapes, 4 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0772",
        "previous_violations": "None",
        "first_contact_on_site": "Security Desk (24hr) — 022-67124000",
        "last_inspection_date": date(2025, 1, 15),
        "inspecting_officer": "Sub Officer C.P. Jagtap",
        "noc_number": "THN/NOC/2024/0789",
        "noc_valid_till": date(2025, 7, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1726,
        "longitude": 72.9480,
    },
    {
        "building_id": "THN-012",
        "name": "Hiranandani Foundation School",
        "building_type": "Educational — School (K-12)",
        "address": "Central Avenue, Hiranandani Estate, Thane – 400607",
        "nearest_landmark": "Hiranandani Estate, near Lake Castle",
        "nbc_occupancy_group": "Group B — Educational",
        "floors_above_ground": 5,
        "floors_below_ground": 1,
        "total_height_metres": 20.0,
        "plot_area_sqm": 8400.0,
        "built_up_area_sqm": 11200.0,
        "daytime_occupancy": 4200,
        "nighttime_occupancy": 0,
        "fire_alarm_make": "Honeywell Morley IAS — Addressable",
        "sprinkler_system": "Yes — corridors, labs, and canteen",
        "internal_hydrants": 10,
        "external_hydrants": 4,
        "wet_riser": "Yes — 2 risers",
        "fire_extinguishers": "CO2 and dry powder — 110 units",
        "panel_model": "Morley-IAS ZX5e",
        "detection_zones": 40,
        "fire_pump_capacity": "900 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — school-wide",
        "generator_backup": "Yes — fire system only",
        "amc_vendor": "Honeywell Building Solutions India",
        "amc_valid_till": date(2025, 9, 30),
        "last_fire_drill": date(2024, 6, 15),
        "drill_attendance_pct": 100,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2006/0681",
        "architect": "Hafeez Contractor Associates",
        "mep_consultant": "Spectral Engineers Pvt Ltd",
        "refuge_floors": "N/A",
        "owner_name": "Hiranandani Foundation",
        "owner_contact": "0251-2578001",
        "entry_points": "Main gate (Central Avenue), Junior wing gate (West), Sports complex gate (East)",
        "exit_routes": "4 staircases, 6 emergency exits, all exit widths 1500mm",
        "previous_noc_number": "THN/NOC/2023/1042",
        "previous_violations": "None",
        "first_contact_on_site": "Reception (school hours) — 0251-2578000",
        "last_inspection_date": date(2024, 6, 21),
        "inspecting_officer": "Sub Officer P.B. Chavan",
        "noc_number": "THN/NOC/2024/1056",
        "noc_valid_till": date(2025, 9, 30),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2570,
        "longitude": 72.9690,
    },
    {
        "building_id": "THN-013",
        "name": "Thane District Court Complex",
        "building_type": "Assembly — Government/Legal",
        "address": "Court Naka, Thane West – 400601",
        "nearest_landmark": "Court Naka, near Thane Station West exit",
        "nbc_occupancy_group": "Group D — Assembly",
        "floors_above_ground": 7,
        "floors_below_ground": 1,
        "total_height_metres": 28.0,
        "plot_area_sqm": 12000.0,
        "built_up_area_sqm": 22000.0,
        "daytime_occupancy": 8000,
        "nighttime_occupancy": 60,
        "fire_alarm_make": "Conventional Zone — Bosch",
        "sprinkler_system": "No",
        "internal_hydrants": 10,
        "external_hydrants": 6,
        "wet_riser": "Yes — 3 risers",
        "fire_extinguishers": "CO2 and dry powder — 140 units",
        "panel_model": "Bosch FPA-5000",
        "detection_zones": 40,
        "fire_pump_capacity": "1200 LPM at 3.5 kg/cm2",
        "public_address_system": "No",
        "generator_backup": "Yes — partial, essential lighting and alarms",
        "amc_vendor": "REMS Security Systems",
        "amc_valid_till": date(2025, 3, 31),
        "last_fire_drill": date(2024, 8, 15),
        "drill_attendance_pct": 82,
        "structural_stability": True,
        "occupancy_certificate": "OC/TMC/2001/0188",
        "architect": "PWD Maharashtra",
        "mep_consultant": "PWD Fire Safety Cell",
        "refuge_floors": "N/A",
        "owner_name": "Government of Maharashtra — PWD",
        "owner_contact": "0251-2302601",
        "entry_points": "Main gate (Court Naka Road), Advocates gate (North side), Accused entry under escort (Rear — restricted)",
        "exit_routes": "5 staircases, 4 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0016",
        "previous_violations": "None",
        "first_contact_on_site": "Court Security (24hr) — 0251-2302600",
        "last_inspection_date": date(2024, 2, 9),
        "inspecting_officer": "Sub Officer R.V. Desai",
        "noc_number": "THN/NOC/2024/0018",
        "noc_valid_till": date(2025, 3, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1985,
        "longitude": 72.9752,
    },
    {
        "building_id": "THN-014",
        "name": "Thane Civil Hospital",
        "building_type": "Institutional — Government Hospital",
        "address": "Dr. Moreshwar Save Marg, Thane West – 400601",
        "nearest_landmark": "Near Thane Station, opposite Court Naka",
        "nbc_occupancy_group": "Group C — Institutional",
        "floors_above_ground": 9,
        "floors_below_ground": 1,
        "total_height_metres": 36.0,
        "plot_area_sqm": 14200.0,
        "built_up_area_sqm": 24000.0,
        "daytime_occupancy": 3600,
        "nighttime_occupancy": 1400,
        "fire_alarm_make": "Conventional Zone — Agni",
        "sprinkler_system": "Partial — ICU, OT, Pharmacy, Blood Bank",
        "internal_hydrants": 18,
        "external_hydrants": 8,
        "wet_riser": "Yes — 5 risers",
        "fire_extinguishers": "CO2, dry powder, water mist — 260 units",
        "panel_model": "Agni FP-4800",
        "detection_zones": 64,
        "fire_pump_capacity": "1800 LPM at 3.5 kg/cm2",
        "public_address_system": "Partial — ward PA only",
        "generator_backup": "Yes — 100%, OT and ICU on UPS",
        "amc_vendor": "Safety Fire Engineers",
        "amc_valid_till": date(2025, 3, 31),
        "last_fire_drill": date(2024, 9, 10),
        "drill_attendance_pct": 77,
        "structural_stability": True,
        "occupancy_certificate": "OC/TMC/2002/0299",
        "architect": "PWD Maharashtra",
        "mep_consultant": "Maharashtra Fire Services Dept",
        "refuge_floors": "N/A",
        "owner_name": "Government of Maharashtra — Health Dept",
        "owner_contact": "0251-2600601",
        "entry_points": "Main gate (Save Marg), Emergency casualty gate (South — 24hr), Mortuary gate (West — restricted)",
        "exit_routes": "6 staircases, 4 emergency exits, dedicated ICU evacuation routes",
        "previous_noc_number": "THN/NOC/2023/0058",
        "previous_violations": "Expired extinguishers in ward 4 (rectified January 2024)",
        "first_contact_on_site": "Main Gate Security (24hr) — 0251-2600600",
        "last_inspection_date": date(2024, 9, 4),
        "inspecting_officer": "Sub Officer K.L. Nikam",
        "noc_number": "THN/NOC/2024/0062",
        "noc_valid_till": date(2025, 3, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1970,
        "longitude": 72.9745,
    },
    {
        "building_id": "THN-015",
        "name": "R-Mall Thane",
        "building_type": "Mercantile — Shopping Mall",
        "address": "Ghantali Road, Naupada, Thane West – 400602",
        "nearest_landmark": "Near Thane Station West, Ghantali Road",
        "nbc_occupancy_group": "Group F — Mercantile",
        "floors_above_ground": 4,
        "floors_below_ground": 2,
        "total_height_metres": 18.0,
        "plot_area_sqm": 14000.0,
        "built_up_area_sqm": 48000.0,
        "daytime_occupancy": 18000,
        "nighttime_occupancy": 0,
        "fire_alarm_make": "Siemens Cerberus — Addressable",
        "sprinkler_system": "Yes — full coverage, 2800 heads",
        "internal_hydrants": 28,
        "external_hydrants": 10,
        "wet_riser": "Yes — 6 risers",
        "fire_extinguishers": "CO2, dry powder, K-class — 220 units",
        "panel_model": "Siemens FC2025",
        "detection_zones": 80,
        "fire_pump_capacity": "2700 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — zone-wise",
        "generator_backup": "Yes — 100%, 48hr diesel",
        "amc_vendor": "Siemens Building Technologies India",
        "amc_valid_till": date(2025, 1, 31),
        "last_fire_drill": date(2024, 11, 3),
        "drill_attendance_pct": 89,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2010/0556",
        "architect": "Design Forum International",
        "mep_consultant": "Meinhardt India Pvt Ltd",
        "refuge_floors": "N/A",
        "owner_name": "R-Mall Developers Pvt Ltd",
        "owner_contact": "0251-6640001",
        "entry_points": "Main entrance (Ghantali Road), Multiplex side entrance, Parking ramp (Basement B1 and B2)",
        "exit_routes": "8 staircases, 6 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0271",
        "previous_violations": "None",
        "first_contact_on_site": "Security Desk (24hr) — 0251-6640000",
        "last_inspection_date": date(2024, 9, 18),
        "inspecting_officer": "Sub Officer D.N. Pawar",
        "noc_number": "THN/NOC/2024/0288",
        "noc_valid_till": date(2025, 1, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1955,
        "longitude": 72.9710,
    },
    {
        "building_id": "THN-016",
        "name": "Suraj Water Park",
        "building_type": "Assembly — Amusement and Recreation",
        "address": "Ghodbunder Road, Majiwada, Thane West – 400601",
        "nearest_landmark": "Majiwada Junction, Ghodbunder Road",
        "nbc_occupancy_group": "Group D — Assembly",
        "floors_above_ground": 3,
        "floors_below_ground": 0,
        "total_height_metres": 14.0,
        "plot_area_sqm": 68000.0,
        "built_up_area_sqm": 12000.0,
        "daytime_occupancy": 8000,
        "nighttime_occupancy": 0,
        "fire_alarm_make": "Conventional Zone — Local Brand",
        "sprinkler_system": "Yes — enclosed structures only",
        "internal_hydrants": 0,
        "external_hydrants": 16,
        "wet_riser": "No",
        "fire_extinguishers": "CO2, dry powder — 80 units",
        "panel_model": "GFE Aries 2000",
        "detection_zones": 24,
        "fire_pump_capacity": "900 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — site-wide outdoor PA",
        "generator_backup": "Partial — alarms only",
        "amc_vendor": "FireTech Services",
        "amc_valid_till": date(2025, 5, 31),
        "last_fire_drill": date(2024, 3, 1),
        "drill_attendance_pct": 83,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2004/0388",
        "architect": "Local Registered Architect",
        "mep_consultant": "FireTech Services",
        "refuge_floors": "N/A",
        "owner_name": "Suraj Water Park Pvt Ltd",
        "owner_contact": "0251-2783001",
        "entry_points": "Main gate (Ghodbunder Road), Emergency exit (North boundary), Staff and vendor entry (East)",
        "exit_routes": "6 emergency exits, 2 main exits, assembly capacity 10,000",
        "previous_noc_number": "THN/NOC/2023/0551",
        "previous_violations": "None",
        "first_contact_on_site": "Main Gate Security — 0251-2783000",
        "last_inspection_date": date(2024, 2, 14),
        "inspecting_officer": "Sub Officer R.D. Rane",
        "noc_number": "THN/NOC/2024/0567",
        "noc_valid_till": date(2025, 5, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2140,
        "longitude": 72.9680,
    },
    {
        "building_id": "THN-017",
        "name": "Eternity Mall",
        "building_type": "Mercantile — Shopping Mall",
        "address": "Manpada Road, Thane West – 400610",
        "nearest_landmark": "Manpada junction, near Ghodbunder Road",
        "nbc_occupancy_group": "Group F — Mercantile",
        "floors_above_ground": 4,
        "floors_below_ground": 2,
        "total_height_metres": 18.0,
        "plot_area_sqm": 18000.0,
        "built_up_area_sqm": 62000.0,
        "daytime_occupancy": 14000,
        "nighttime_occupancy": 0,
        "fire_alarm_make": "Conventional Zone — Agni",
        "sprinkler_system": "Yes — partial (retail floors only)",
        "internal_hydrants": 22,
        "external_hydrants": 8,
        "wet_riser": "Yes — 4 risers",
        "fire_extinguishers": "CO2, dry powder, K-class — 180 units",
        "panel_model": "Agni FP-3200",
        "detection_zones": 64,
        "fire_pump_capacity": "1800 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — zone-wise",
        "generator_backup": "Yes — 100%, 48hr diesel",
        "amc_vendor": "Safety Fire Engineers",
        "amc_valid_till": date(2025, 6, 30),
        "last_fire_drill": date(2024, 12, 8),
        "drill_attendance_pct": 85,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2011/0712",
        "architect": "Design Forum International",
        "mep_consultant": "Consulting Engineers Group",
        "refuge_floors": "N/A",
        "owner_name": "Eternity Estates Pvt Ltd",
        "owner_contact": "0251-6698001",
        "entry_points": "Main entrance (Manpada Road), Side entrance (South), Basement parking ramp",
        "exit_routes": "6 staircases, 6 emergency exits",
        "previous_noc_number": "THN/NOC/2023/0726",
        "previous_violations": "None",
        "first_contact_on_site": "Security Counter — 0251-6698000",
        "last_inspection_date": date(2024, 12, 12),
        "inspecting_officer": "Sub Officer G.A. Salvi",
        "noc_number": "THN/NOC/2024/0743",
        "noc_valid_till": date(2025, 6, 30),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2280,
        "longitude": 72.9720,
    },
    {
        "building_id": "THN-018",
        "name": "Balkum Bus Depot — MSRTC",
        "building_type": "Storage — Transportation Fleet",
        "address": "Balkum, Thane West – 400608",
        "nearest_landmark": "Balkum Naka, near Wagle Estate junction",
        "nbc_occupancy_group": "Group H — Storage",
        "floors_above_ground": 2,
        "floors_below_ground": 0,
        "total_height_metres": 8.0,
        "plot_area_sqm": 28000.0,
        "built_up_area_sqm": 8000.0,
        "daytime_occupancy": 420,
        "nighttime_occupancy": 80,
        "fire_alarm_make": "Conventional Zone — Local Brand",
        "sprinkler_system": "No",
        "internal_hydrants": 0,
        "external_hydrants": 12,
        "wet_riser": "No",
        "fire_extinguishers": "CO2, dry powder, foam (diesel area) — 64 units",
        "panel_model": "GFE Aries 1000",
        "detection_zones": 16,
        "fire_pump_capacity": "600 LPM at 3.5 kg/cm2",
        "public_address_system": "No",
        "generator_backup": "Partial — alarms only",
        "amc_vendor": "FireTech Services",
        "amc_valid_till": date(2025, 5, 31),
        "last_fire_drill": date(2024, 4, 14),
        "drill_attendance_pct": 91,
        "structural_stability": True,
        "occupancy_certificate": "OC/TMC/2001/0504",
        "architect": "MSRTC Engineering Division",
        "mep_consultant": "MSRTC Fire Safety Cell",
        "refuge_floors": "N/A",
        "owner_name": "Maharashtra State Road Transport Corporation",
        "owner_contact": "0251-2382001",
        "entry_points": "Main bus entry/exit gate (Balkum Road — 7m wide), Workshop entry (East), Staff gate (North)",
        "exit_routes": "4 exits, 2 vehicle evacuation routes",
        "previous_noc_number": "THN/NOC/2023/0608",
        "previous_violations": "None",
        "first_contact_on_site": "Depot Gate (24hr) — 0251-2382000",
        "last_inspection_date": date(2024, 4, 16),
        "inspecting_officer": "Sub Officer V.D. Kadam",
        "noc_number": "THN/NOC/2024/0622",
        "noc_valid_till": date(2025, 5, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2070,
        "longitude": 72.9560,
    },
    {
        "building_id": "THN-019",
        "name": "Thane Railway Station",
        "building_type": "Assembly — Transportation (Major)",
        "address": "Station Road, Thane East – 400603",
        "nearest_landmark": "Thane Main Station — Central and Harbour Line junction",
        "nbc_occupancy_group": "Group D — Assembly",
        "floors_above_ground": 3,
        "floors_below_ground": 0,
        "total_height_metres": 14.0,
        "plot_area_sqm": 22000.0,
        "built_up_area_sqm": 18000.0,
        "daytime_occupancy": 180000,
        "nighttime_occupancy": 8000,
        "fire_alarm_make": "Conventional Zone — Bosch (Railway spec)",
        "sprinkler_system": "No",
        "internal_hydrants": 0,
        "external_hydrants": 24,
        "wet_riser": "No",
        "fire_extinguishers": "CO2 and dry powder — 240 units (platform)",
        "panel_model": "Bosch FPA-1200 (Railway spec)",
        "detection_zones": 32,
        "fire_pump_capacity": "1200 LPM at 3.5 kg/cm2",
        "public_address_system": "Yes — integrated railway PA, full platform coverage",
        "generator_backup": "Yes — full backup, diesel + UPS",
        "amc_vendor": "Central Railway Fire Safety Division",
        "amc_valid_till": date(2024, 12, 31),
        "last_fire_drill": date(2024, 5, 1),
        "drill_attendance_pct": 95,
        "structural_stability": True,
        "occupancy_certificate": "Railway Board Clearance RB/2002/THN",
        "architect": "Central Railway Design Bureau",
        "mep_consultant": "Central Railway Fire Safety Division",
        "refuge_floors": "N/A",
        "owner_name": "Central Railway — Ministry of Railways (Government)",
        "owner_contact": "0251-2300701",
        "entry_points": "West entrance (Station Road — main), East entrance (Gokhale Road), FOB connections to adjoining roads",
        "exit_routes": "12 exits across all platforms, 4 FOBs, 2 underpasses",
        "previous_noc_number": "THN/NOC/2023/0051",
        "previous_violations": "None",
        "first_contact_on_site": "RPF Control Room (24hr) — 0251-2300700",
        "last_inspection_date": date(2024, 5, 11),
        "inspecting_officer": "Div. Officer A.M. Kulkarni",
        "noc_number": "THN/NOC/2024/0055",
        "noc_valid_till": date(2024, 12, 31),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.1860,
        "longitude": 72.9750,
    },
    {
        "building_id": "THN-020",
        "name": "Viviana Mall — Tower B (Office Wing)",
        "building_type": "Business — Commercial Office",
        "address": "Pokhran Road No. 2, Thane West – 400610",
        "nearest_landmark": "Adjacent to Viviana Mall, Thane West",
        "nbc_occupancy_group": "Group E — Business",
        "floors_above_ground": 18,
        "floors_below_ground": 3,
        "total_height_metres": 72.0,
        "plot_area_sqm": 6200.0,
        "built_up_area_sqm": 28400.0,
        "daytime_occupancy": 4800,
        "nighttime_occupancy": 200,
        "fire_alarm_make": "Honeywell Notifier — Addressable",
        "sprinkler_system": "Yes — full building, 1800 heads",
        "internal_hydrants": 20,
        "external_hydrants": 6,
        "wet_riser": "Yes — 4 pressurised risers",
        "fire_extinguishers": "CO2 and dry powder — 180 units",
        "panel_model": "Notifier NFS2-3030",
        "detection_zones": 96,
        "fire_pump_capacity": "1800 LPM at 4.5 kg/cm2",
        "public_address_system": "Yes — floor-wise addressable",
        "generator_backup": "Yes — 100%, 48hr diesel",
        "amc_vendor": "Honeywell Building Solutions India",
        "amc_valid_till": date(2025, 11, 30),
        "last_fire_drill": date(2024, 10, 2),
        "drill_attendance_pct": 88,
        "structural_stability": True,
        "occupancy_certificate": "OC/THN/2021/1688",
        "architect": "RSP Architects",
        "mep_consultant": "Meinhardt India Pvt Ltd",
        "refuge_floors": "6th, 12th, 18th floor",
        "owner_name": "Viviana Malls Pvt Ltd — Commercial Division",
        "owner_contact": "0251-6690002",
        "entry_points": "Main lobby (Pokhran Road), Basement parking ramp (East), Service entry (Rear — goods lift access)",
        "exit_routes": "4 pressurised staircases, 2 fire escapes, fire lift on each staircore",
        "previous_noc_number": "THN/NOC/2023/1142",
        "previous_violations": "None",
        "first_contact_on_site": "Lobby Security Desk (24hr) — 0251-6690010",
        "last_inspection_date": date(2024, 10, 28),
        "inspecting_officer": "Sub Officer P.R. Kulkarni",
        "noc_number": "THN/NOC/2024/1198",
        "noc_valid_till": date(2025, 11, 30),
        "is_high_hazard": False,
        "floorplan_path": "noc_data/floorplan.svg",
        "latitude": 19.2088,
        "longitude": 72.9765,
    },
]

# ── Fire stations (dummy for Thane jurisdiction) ──

FIRE_STATIONS = [
    {
        "id": 1,
        "name": "Thane Main Fire Station",
        "address": "Naupada, Thane West – 400602",
        "latitude": 19.1968,
        "longitude": 72.9726,
        "phone": "0251-2533101",
    },
    {
        "id": 2,
        "name": "Wagle Estate Fire Station",
        "address": "MIDC Wagle Estate, Thane West – 400604",
        "latitude": 19.2055,
        "longitude": 72.9590,
        "phone": "0251-2533102",
    },
    {
        "id": 3,
        "name": "Ghodbunder Road Fire Station",
        "address": "Majiwada, Ghodbunder Road, Thane West – 400601",
        "latitude": 19.2310,
        "longitude": 72.9670,
        "phone": "0251-2533103",
    },
    {
        "id": 4,
        "name": "Kalwa Fire Station",
        "address": "Kalwa, Thane – 400605",
        "latitude": 19.1930,
        "longitude": 73.0010,
        "phone": "0251-2533104",
    },
    {
        "id": 5,
        "name": "Mulund Fire Station",
        "address": "LBS Marg, Mulund West, Mumbai – 400080",
        "latitude": 19.1730,
        "longitude": 72.9500,
        "phone": "022-25633105",
    },
]

# ── Building-to-station mapping (nearest station) ──

BUILDING_STATION_MAP = [
    {"building_id": "THN-001", "fire_station_id": 5},   # Vidyavihar → Mulund
    {"building_id": "THN-002", "fire_station_id": 1},   # Jupiter Hospital → Thane Main
    {"building_id": "THN-003", "fire_station_id": 1},   # Viviana Mall → Thane Main
    {"building_id": "THN-004", "fire_station_id": 3},   # Hiranandani Estate → Ghodbunder
    {"building_id": "THN-005", "fire_station_id": 1},   # TMC Office → Thane Main
    {"building_id": "THN-006", "fire_station_id": 1},   # Bhabha Hospital → Thane Main
    {"building_id": "THN-007", "fire_station_id": 3},   # Lodha Amara → Ghodbunder
    {"building_id": "THN-008", "fire_station_id": 3},   # Korum Mall → Ghodbunder
    {"building_id": "THN-009", "fire_station_id": 2},   # Wagle Industrial → Wagle Estate
    {"building_id": "THN-010", "fire_station_id": 4},   # BPCL → Kalwa
    {"building_id": "THN-011", "fire_station_id": 5},   # Fortis Mulund → Mulund
    {"building_id": "THN-012", "fire_station_id": 3},   # Hiranandani School → Ghodbunder
    {"building_id": "THN-013", "fire_station_id": 1},   # Court Complex → Thane Main
    {"building_id": "THN-014", "fire_station_id": 1},   # Civil Hospital → Thane Main
    {"building_id": "THN-015", "fire_station_id": 1},   # R-Mall → Thane Main
    {"building_id": "THN-016", "fire_station_id": 3},   # Suraj Water Park → Ghodbunder
    {"building_id": "THN-017", "fire_station_id": 3},   # Eternity Mall → Ghodbunder
    {"building_id": "THN-018", "fire_station_id": 2},   # Balkum Bus Depot → Wagle Estate
    {"building_id": "THN-019", "fire_station_id": 1},   # Railway Station → Thane Main
    {"building_id": "THN-020", "fire_station_id": 1},   # Viviana Tower B → Thane Main
]


async def seed():
    """Drop all tables, recreate, and seed with dummy data."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        # Seed buildings
        for b in BUILDINGS:
            session.add(Building(**b))

        # Seed fire stations
        for fs in FIRE_STATIONS:
            session.add(FireStation(**fs))

        await session.flush()

        # Seed building-station mappings
        for bsm in BUILDING_STATION_MAP:
            session.add(BuildingStationMap(**bsm))

        await session.commit()

    print(f"✅ Seeded {len(BUILDINGS)} buildings")
    print(f"✅ Seeded {len(FIRE_STATIONS)} fire stations")
    print(f"✅ Seeded {len(BUILDING_STATION_MAP)} building-station mappings")
    print("Database ready!")


if __name__ == "__main__":
    asyncio.run(seed())